# Background and foreground colors
background = #0D1206
foreground = #E1E0D9

# Standard colors
palette = 0=#0D1206
palette = 1=#a08034
palette = 2=#5b8f2c
palette = 3=#b7b966
palette = 4=#6378c1
palette = 5=#647fc7
palette = 6=#5a80c5
palette = 7=#E1E0D9

# Bright colors
palette = 8=#686b65
palette = 9=#c8a53d
palette = 10=#79b825
palette = 11=#d4d968
palette = 12=#8599f7
palette = 13=#86a1fd
palette = 14=#7ba2fb
palette = 15=#f1edc6
