background            #0D1206
foreground            #E1E0D9

# black
color0  #0D1206
color8  #686b65

# red
color1  #a08034
color9  #c8a53d

# green
color2  #5b8f2c
color10 #79b825

# yellow
color3  #b7b966
color11 #d4d968

# blue
color4  #6378c1
color12 #8599f7

# magenta
color5  #647fc7
color13 #86a1fd

#cyan
color6  #5a80c5
color14 #7ba2fb

#white
color7  #E1E0D9
color15 #f1edc6


